### ISSUE TITLE
The Number conversion does not work correctly

### ISSUE THREAD

**Issue by ChipsetX86** [IvanPinezhaninov/QDbf#5]
I work with the Russian FIAS system [(example DBF file),](https://yadi.sk/d/xZ4XICdV3MrYSv) there is used the Number (2 bytes) type, the library does not handle it correctly considering the data as a double
Here is the version of the code that works:

`        case QDbfField::Number:
        {
            value = QString::fromAscii(byteArray).toInt();
            break;
        }`

**Comment by IvanPinezhaninov** [comment]
Hi! The number data type includes a decimal point so it can't be considered as an integer value. You can use the QDbfField::precision() method for decision to convert value to integer in your code.

You can read about data types [here](https://www.clicketyclick.dk/databases/xbase/format/data_types.html).

**Comment by ChipsetX86** [comment]
Problem with the method QDbfTable::record
`case QDbfField::FloatingPoint:
        case QDbfField::Number:
            value = byteArray.toDouble();`
Invalid conversion of ASCII to double

**Comment by IvanPinezhaninov** [comment]
What data the byteArray variable contains at the time of the error?

**Comment by ChipsetX86** [comment]
example `0x20 0x30 ` which corresponds to 0

**Comment by ChipsetX86** [comment]
open the file I sent to you [(example DBF file),](https://yadi.sk/d/xZ4XICdV3MrYSv) in my program QDbfExample (column ACTSTATUS)

**Comment by IvanPinezhaninov** [comment]
I can't understand what the problem is. Field ACTSTATUS has Number type with precision = 0.
`0x20 0x30` corresponds to `" 0"` and converted to 0.
`0x20 0x31` corresponds to `" 1"` and converted to 1.
What is wrong?

**Comment by ChipsetX86** [comment]
In the current version of the program QDbfExample , the value is always 0

**Comment by ChipsetX86** [comment]
![sc](https://user-images.githubusercontent.com/5338188/30432653-fb84fa1a-996a-11e7-8627-9642525ab06f.jpg)

**Comment by IvanPinezhaninov** [comment]
It is very strangeful. QByteArray::toDouble() is a standard method and i wonder why it isn't working in your case.

**Comment by IvanPinezhaninov** [comment]
Maybe you'll try to debug this part of the code on your system in order to find out why this code does not work correctly.

**Comment by IvanPinezhaninov** [comment]
For your convenience, I have committed changes that allow consider numeric fields defined with zero precision as integer instead of a double.

**Comment by ChipsetX86** [comment]
It works now. But I think it's better to use QString::fromAscii (byteArray) instead of trimmed()
