### ISSUE TITLE
can't open  QDbfd.lib

### ISSUE THREAD

**Issue by sam5945** [IvanPinezhaninov/QDbf#9]
where i import it into Qt creator ,and run the main.cpp in example.it has probrem.can't open "QDbfd.lib"  file.I'm a beginner

**Comment by IvanPinezhaninov** [comment]
Unfortunately I do not have Windows and I can not see this error. But you can use the advice from this topic: https://forum.qt.io/topic/24427/how-to-use-qdbf-under-windows

**Comment by over-infinity** [comment]
Hello,
when I insert a few records(for example from my own database) it does not save records and just last record will save.
you can test it by adding multiple records and try to give them some values. so when you close and open file just values of last record will save into last file record. so I analysis your source code and notice that  you should add following changes into your source code.
in function QDbfTable::addRecord() add below line before returning:
 newRecord.setRecordIndex(size()+1);
 return addRecord(newRecord);

and in function QDbfTable::setRecord add below line after for loop:
 d->m_currentIndex=record.recordIndex();

by adding these lines you can add multiple records and it works correctly.
please check it and let me know if everything is ok.
